### ISSUE TITLE
Could you kindly share your future research plans?

### ISSUE THREAD

**Issue by esmusssein09** [YibooZhao/Local-Control#2]
Dear author,

Greetings. It is truly an honor to have had the opportunity to read your magnificent work. Firstly, I hold immense respect for your spirit of open-source collaboration. Secondly, I deeply appreciate the significant contributions outlined in your paper. Lastly, I sincerely hope that your paper receives prompt acceptance.

Moreover, as you haven't mentioned your future work in the paper, would it be possible to have the chance to discuss it with you? I am immensely grateful for your consideration.

Best regards.

**Comment by chengkenyong** [comment]
I also would like to understand

**Comment by chengkenyong** [comment]
I would like to know your plans

**Comment by chengkenyong** [comment]
I would like to know your plans as well
